Feature/co 48
IT-Minds/client_comby_oilcontrols pull request #14
Opened 2021-01-11 09:22 UTC by DanielVelando

2021-01-11 10:18 UTC, objmj-itminds requested changes

2021-01-11 10:18 UTC, objmj-itminds commented on frontend/src/components/Camera/CameraComponent.tsx
> +            screenshotFormat="image/jpeg"
can this be png or webp ?

2021-01-11 10:18 UTC, objmj-itminds commented on frontend/src/components/Camera/CameraComponent.tsx
> +      <Box className={styles.marginTop}>
Maybe we can look at the Center component
https://chakra-ui.com/docs/layout/center

2021-01-11 10:18 UTC, objmj-itminds commented on frontend/src/components/Camera/styles.module.css
> +.code {
remove all the unneeded style classes

2021-01-11 10:18 UTC, objmj-itminds commented on package-lock.json
> +    "react-webcam": {
I think you installed react-webcam in the wrong dir.
In any case, this root dir should not have this package-lock change, and the frontend sub dir is missing it.

2021-01-11 11:12 UTC, DanielVelando commented on package-lock.json
> +    "react-webcam": {
It is installed in "/frontend", I'm not sure what you mean?

2021-01-11 11:21 UTC, objmj-itminds commented on package-lock.json
> +    "react-webcam": {
It isn't part of the package-lock file. Try to do another `npm i` in /frontend and commit the lock file.

2021-01-11 11:47 UTC, objmj-itminds commented on package-lock.json
> +    "react-webcam": {
I see it updated in the frontend dir, now this section has to be removed, and it is all good.

2021-01-11 11:49 UTC, objmj-itminds commented on frontend/src/pages/demo/camera.tsx
> +        <CameraComp imgSource={setImgSource} />
Can you add a screenshot?

2021-01-11 11:50 UTC, DanielVelando commented on package-lock.json
> +    "react-webcam": {
Yea I saw one of the checks failed and asked me to do another npm i - should be fine now!

2021-01-11 11:51 UTC, DanielVelando commented on frontend/src/pages/demo/camera.tsx
> +        <CameraComp imgSource={setImgSource} />
As in select an image to preview and not only capture one?

2021-01-11 11:54 UTC, objmj-itminds requested changes

2021-01-11 11:54 UTC, objmj-itminds commented on frontend/src/components/Camera/CameraComponent.tsx
> +  const webcamRef = useRef(null);
You should type this to the expected ref type. 
example:
```typescript
useRef<LegacyRef<HTMLVideoElement>>(null);
```
Hint you can check the type akin
```typescript
useRef<ClassAttributes<HTMLVideoElement>.ref>(null);
```

2021-01-11 11:54 UTC, objmj-itminds commented on frontend/src/components/Camera/CameraComponent.tsx
> +  }, [webcamRef]);
webcamRef is a ref which never provides any state dispatches.

> Keep in mind that useRef doesn’t notify you when its content changes. Mutating the .current property doesn’t cause a re-render. If you want to run some code when React attaches or detaches a ref to a DOM node, you may want to use a callback ref instead.
source: https://reactjs.org/docs/hooks-reference.html#useref

2021-01-11 11:54 UTC, objmj-itminds commented on frontend/src/components/Camera/CameraComponent.tsx
> +  imgSource: (x: any) => void;
You should know the source of this `x` from the `getScreenshot()`. That type should be deterministic.

2021-01-11 11:56 UTC, objmj-itminds commented on frontend/src/pages/demo/camera.tsx
> +        <CameraComp imgSource={setImgSource} />
Like a screenshot in this PR of how the component looks, hint you can paste in any image from your clipboard, and GitHub will automatically host it.

2021-01-11 11:59 UTC, DanielVelando commented on frontend/src/pages/demo/camera.tsx
> +        <CameraComp imgSource={setImgSource} />
![image](https://user-images.githubusercontent.com/54571314/104179838-c49e9500-540c-11eb-97eb-0d3e927ec8fe.png)

2021-01-12 07:15 UTC, DanielVelando commented on frontend/src/components/Camera/CameraComponent.tsx
> +      <Box className={styles.marginTop}>
How about VStack?
https://chakra-ui.com/docs/layout/stack

It will put elements inside it vertically AND centers them as well!

2021-01-12 08:15 UTC, objmj-itminds approved these changes

2021-01-12 08:16 UTC, merged