CO-62 Mark coupons as invalid/destroyed
IT-Minds/client_comby_oilcontrols pull request #24
Opened 2021-01-12 13:50 UTC by JeppeTrip

2021-01-12 19:57 UTC, objmj-itminds commented
Try the rebase of this branch 
`git fetch && git rebase origin/main`

2021-01-12 20:00 UTC, objmj-itminds approved these changes
LGTM
Only a very minor issue.

2021-01-12 20:00 UTC, objmj-itminds commented on backend/Application/Coupon/Commands/UpdateCouponStatus/UpdateCouponStatusCommand.cs
> +        var coupon = coupons.FirstOrDefault(x => x.CouponNumber == request.CouponNumber);
Combine into one line by chaining the statements

2021-01-12 20:00 UTC, objmj-itminds commented on backend/Application/Coupon/Commands/UpdateCouponStatus/UpdateCouponStatusCommand.cs
> +        var coupon = coupons.FirstOrDefault(x => x.CouponNumber == request.CouponNumber);
```csharp
_context.Coupons.FirstOrDefault(x => x.TruckId == request.TruckId && x.CouponNumber == request.CouponNumber);
```
Is also an option

2021-01-13 20:13 UTC, objmj-itminds requested changes
API Endpoint missing.

I would like it to be
`PUT /coupon/{id}/invalidate`

2021-01-14 09:06 UTC, objmj-itminds requested changes

2021-01-14 09:06 UTC, objmj-itminds commented on backend/Web/Controllers/CouponsController.cs
> +    public async Task<ActionResult<int>> Update(int id, UpdateCouponStatusCommand command)
Not sure what best practice is, but the tags [FromRoute]  can help a lot and explicitly tells the developers where you are requesting this param from.

2021-01-14 09:06 UTC, objmj-itminds commented on backend/Web/Controllers/CouponsController.cs
> +    public async Task<ActionResult<int>> Update(int id, UpdateCouponStatusCommand command)
Oh, and name the method something akin to the route, so here.
`Invalidate` would have been preferable. It impacts the nswagts generation, so the frontend knows what function they are using.

2021-01-14 09:06 UTC, objmj-itminds commented on backend/Application/Coupons/Commands/UpdateCouponStatus/UpdateCouponStatusCommand.cs
> +    public int CouponNumber { get; set; }
Now that we have the ID from the route, we can trash these and simply use `.Find` to get that one coupon

2021-01-14 11:51 UTC, JeppeTrip commented on backend/Application/Coupons/Commands/UpdateCouponStatus/UpdateCouponStatusCommand.cs
> +    public int CouponNumber { get; set; }
Not quite sure I understand what you mean here? 
The way I see it is that we need the CouponNumber to find the Coupon and a TruckId to make sure that we aren't messing with other vehicles coupons. I don't know how the route fits in? We want to be able to invalidate coupons that aren't necessarily used yet, and thus have no relation to any route.

2021-01-14 11:52 UTC, CSCITM commented on backend/Web/Controllers/CouponsController.cs
> +    [HttpPut("/coupon/{id}/invalidate")]
When you are using ApiControllerBase, it will add the base route [Route("api/[controller]")] to all endpoints.
So your route will end up being: api/coupons/coupon/{id}/invalidate currently?

2021-01-14 12:01 UTC, objmj-itminds commented on backend/Application/Coupons/Commands/UpdateCouponStatus/UpdateCouponStatusCommand.cs
> +    public int CouponNumber { get; set; }
the controller route. Right now the current path takes the specific ID from the coupon to invalidate, so we don't need a body with that action and can safely use that id with a `.Find`

2021-01-14 14:35 UTC, objmj-itminds approved these changes

2021-01-14 14:54 UTC, merged