WIP/CO-69 Expand datamodel for location/refilll metadata
IT-Minds/client_comby_oilcontrols pull request #35
Opened 2021-01-13 10:34 UTC by JeppeTrip

Please take a look at the changes I made to the data-model and see if you agree with these.
I haven't added in the images just yet. How are we supposed to save these, as blob or just to the filesystem as we do with the coupons?

2021-01-13 19:24 UTC, objmj-itminds commented
> How are we supposed to save these, as blob or just to the filesystem as we do with the coupons?
Yeah, set a different config for this path.

> Should a location be able to have more than 1 fuel tank assigned?
Let us start with 1, if we end up missing this requirement then I blame the specs.

2021-01-14 09:08 UTC, objmj-itminds commented
No clue how you manage to create these branches that are so out of sync that they destroy GitHub's PR system. 
Don't touch this branch - I'll clean It up.

2021-01-14 09:30 UTC, objmj-itminds requested changes

2021-01-14 09:30 UTC, objmj-itminds commented on backend/Application/Refills/Commands/CreateRefill/CreateRefillCommand.cs
> +        var Location = await _context.Locations.FirstOrDefaultAsync(x => x.FuelTank.Type == request.TankType && x.FuelTank.TankNumber == request.TankNumber);
I believe you need to use `.Include()` to attach the relation to the query

2021-01-14 09:30 UTC, objmj-itminds commented on backend/Application/Refills/Queries/GetRefillsQuery.cs
> +                .Where(x => x.Location.FuelTank.Type == request.TankType && x.Location.FuelTank.TankNumber == request.TankNumber)
I believe you need to use `.Include()` to attach the relation to the query.
Which for the pagination required you to do so on the base query

2021-01-14 09:30 UTC, objmj-itminds commented on backend/Domain/Enums/RefillSchedule.cs
> +    MANUAL
Assign values

2021-01-14 09:30 UTC, objmj-itminds commented on backend/Infrastructure/Persistence/Migrations/20210113102831_FuelTankEntity.cs
> +            migrationBuilder.RenameColumn(
This could cause issues as the old enum values might not correspond to the new enum.

2021-01-14 11:47 UTC, CSCITM reviewed
Remember to use Include to ensure you get all data needed in your queries.

2021-01-14 12:09 UTC, objmj-itminds requested changes

2021-01-14 12:09 UTC, objmj-itminds commented on backend/Application/Refills/Queries/GetRefillsQuery.cs
> +        var baseQuery = _context.Refills.Include("Location").Include("Location.FuelTank");
Instead of strings, you can use a lambda function; this is preferred as it allows for easy refactoring.

```csharp
context.Refills
  .Include(refill => refill.Location)
    .ThenInclude(location => location.FuelTank);
```

2021-01-14 12:09 UTC, objmj-itminds commented on backend/Application/Refills/Commands/CreateRefill/CreateRefillCommand.cs
> +        var Location = await _context.Locations
Instead of strings, you can use a lambda function; this is preferred as it allows for easy refactoring.
see ackend/Application/Refills/Queries/GetRefillsQuery.cs:66 comment

2021-01-15 08:09 UTC, objmj-itminds submitted a review, later dismissed

2021-01-15 08:12 UTC, objmj-itminds submitted a review, later dismissed

2021-01-15 12:31 UTC, objmj-itminds commented
I'll clean this PR up. ETA 1 hour

2021-01-15 14:52 UTC, objmj-itminds approved these changes

2021-01-15 15:16 UTC, objmj-itminds approved these changes

2021-01-15 15:16 UTC, merged