WIP/CO-68 Expand datamodel to represent truck fueltank state.
IT-Minds/client_comby_oilcontrols pull request #36
Opened 2021-01-13 10:45 UTC by JeppeTrip

Problems with the database not updating as it should (which is why I also added the dbscript into this commit).

2021-01-13 19:28 UTC, objmj-itminds requested changes
Maybe the cause due to an empty migration. I can help you look at this isuee.

2021-01-13 19:28 UTC, objmj-itminds commented on backend/Domain/Entities/TruckState.cs
> +    public ICollection<TruckRefill> Refills { get; set; }
Let's reverse this and put a Truck and TruckId into the TruckRefill entity

2021-01-13 19:28 UTC, objmj-itminds commented on backend/Domain/Entities/Truck.cs
> +    public ICollection<TruckState> DailyStates { get; set; }
Let's reverse this and put a Truck and TruckId into the TruckState entity.

We can always keep these as `virtual`

2021-01-14 08:00 UTC, JeppeTrip commented on backend/Domain/Entities/TruckState.cs
> +    public ICollection<TruckRefill> Refills { get; set; }
You mean put the TruckState and TruckStateId into TruckRefill entity for this one, right?

2021-01-14 11:43 UTC, CSCITM commented on backend/Infrastructure/Persistence/Migrations/20210113092515_TruckStateAndRefillsModel.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Remove empty migration

2021-01-14 11:43 UTC, CSCITM commented on backend/Domain/Entities/TruckState.cs
> +    public virtual ICollection<TruckRefill> Refills { get; set; }
I see virtual in this PR but not in the other, any reason?

2021-01-14 11:43 UTC, CSCITM commented on backend/Web/dbscript
> +﻿CREATE TABLE [ExampleEntityLists] (
What is the use of this?

2021-01-14 12:14 UTC, objmj-itminds commented
I think the best approach is to sorta "start from scratch" with this. A whole new branch from main and then restart with the entities and migrations.

2021-01-14 12:15 UTC, closed without merging

2021-01-14 12:15 UTC, objmj-itminds commented on backend/Domain/Entities/TruckState.cs
> +    public ICollection<TruckRefill> Refills { get; set; }
Yes