CO-76 Create daily temperature for a region.
IT-Minds/client_comby_oilcontrols pull request #45
Opened 2021-01-14 09:54 UTC by JeppeTrip

2021-01-14 09:55 UTC, JeppeTrip commented on backend/Domain/Entities/Region.cs
> +      DailyTemperatures = new List<RegionDailyTemp>();
Should we be instantiating the lists in all of the entities, to ensure null pointers doesn't occur in the commands?

2021-01-14 11:39 UTC, CSCITM requested changes

2021-01-14 11:39 UTC, CSCITM commented on backend/Domain/Entities/Region.cs
> +      DailyTemperatures = new List<RegionDailyTemp>();
This should not be needed

2021-01-14 11:39 UTC, CSCITM commented on backend/Application/DailyTemperatures/Commands/CreateDailyTemperatureCommand.cs
> +        var temp = region.DailyTemperatures.FirstOrDefault(x => x.Date == request.Date);
I don't see the DailyTemperatures included in the region query.

2021-01-14 12:19 UTC, objmj-itminds requested changes

2021-01-14 12:19 UTC, objmj-itminds commented on backend/Application/DailyTemperatures/Commands/CreateDailyTemperatureCommand.cs
> +        var region = _context.Regions.FirstOrDefault(x => x.Id == request.RegionId);
missing include

2021-01-14 12:19 UTC, objmj-itminds commented on backend/Domain/Entities/Region.cs
> +      DailyTemperatures = new List<RegionDailyTemp>();
If you need a default value you can write it in the lines above like

`public ICollection<RegionDailyTemp> DailyTemperatures { get; set; } = new List<RegionDailyTemp>();`

2021-01-14 12:20 UTC, objmj-itminds approved these changes

2021-01-14 12:20 UTC, objmj-itminds commented on backend/Application/DailyTemperatures/Commands/CreateDailyTemperatureCommand.cs
> +          .Include("DailyTemperatures").
Use lambda for includes.
And format with the period on new line.

2021-01-14 12:21 UTC, CSCITM requested changes

2021-01-14 12:21 UTC, CSCITM commented on backend/Application/DailyTemperatures/Commands/CreateDailyTemperatureCommand.cs
> +        var temp = region.DailyTemperatures.FirstOrDefault(x => x.Date == request.Date);
This is not resolved.

2021-01-14 12:21 UTC, CSCITM commented on backend/Domain/Entities/Region.cs
> +      DailyTemperatures = new List<RegionDailyTemp>();
Default values is generally not needed for entity lists.

2021-01-14 12:29 UTC, CSCITM requested changes

2021-01-14 12:29 UTC, CSCITM commented on backend/Application/DailyTemperatures/Commands/CreateDailyTemperatureCommand.cs
> +          .Include("DailyTemperatures").
As Martin said use lambda for includes, this will break with no warnings if you rename DailyTemperatures.

2021-01-15 08:46 UTC, objmj-itminds approved these changes

2021-01-15 15:17 UTC, merged