WIP/CO-70 Update meta  data.
IT-Minds/client_comby_oilcontrols pull request #64
Opened 2021-01-18 09:38 UTC by JeppeTrip

So I made a basic command but do have some questions about the implementation. 
Should `UpdateLocationMetaDataCommand` be split into multiple commands, since it logically covers a couple of types of metadata: (1) Data related to the location it self such as address, comment, the picture showing tank placement. (2) Metadata related to the tank it self such as, capacity, minimum fuel amount, estimated consumption.

Should the upload of the image be its own command/api end point as well?

2021-01-18 09:47 UTC, objmj-itminds commented
> Should UpdateLocationMetaDataCommand be split into multiple commands
> ...
> Should the upload of the image be its own command/api end point as well?

Put the image into its own command. The rest can make sense to have together.

2021-01-18 13:39 UTC, objmj-itminds requested changes
Looks good - we do need one minor change that requires some edit in multiple additional files.

2021-01-18 13:39 UTC, objmj-itminds commented on backend/Application/Locations/Commands/AddLocationImageCommand.cs
> +      public AddLocationImageCommandHandler(IApplicationDbContext context, IOptions<FileDriveOptions> options)
We need to expand this option to support the different types of stored files. 
Look at adding multiple "paths" attribute with a naming that specifies the different types of images

2021-01-19 08:58 UTC, CSCITM commented on backend/Application.UnitTests/Locations/Commands/UpdateLocationMetaData/UpdateLocationMetaDataCommandTest.cs
> +    public async Task Handle_ShouldPersistNewData()
You should test faulty stuff like exceptions and such too.

2021-01-19 08:58 UTC, CSCITM commented on backend/Application/Coupons/Commands/SaveCouponImage/SaveCouponImageCommand.cs
> +          throw new ArgumentException("No refill with ID: " + request.RefillId);
You should use or add exception types handled in ApiExceptionFilterAttribute, to ensure the backend will return the correct status code and exception details.

2021-01-19 08:58 UTC, CSCITM commented on backend/Application/Locations/Commands/AddLocationImageCommand.cs
> +        if (png.IsMatch(request.Picture.ContentType))
If you need to support more filetypes this will end up being a mess. You could use or in the regex etc. to check for correctness and grab filetype afterwards, then you would only need to maintain the list of allowed file extensions.

2021-01-19 12:31 UTC, JeppeTrip commented on backend/Application.UnitTests/Locations/Commands/UpdateLocationMetaData/UpdateLocationMetaDataCommandTest.cs
> +    public async Task Handle_ShouldPersistNewData()
I'm currently getting some answers as to how we should handle some of these things, will update the tests as soon as possible.

2021-01-19 16:08 UTC, objmj-itminds approved these changes

2021-01-19 16:09 UTC, merged