CO-51 Expand Data Model for Refills
IT-Minds/client_comby_oilcontrols pull request #7
Opened 2021-01-08 10:05 UTC by JeppeTrip

Added a basic data model that should give us the ability to register refills on buildings.

2021-01-08 11:41 UTC, objmj-itminds requested changes

2021-01-08 11:41 UTC, objmj-itminds commented on backend/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
> -﻿// <auto-generated />
Not a fan of this file being fully replaced. Not sure what the formatting difference is. I will have to pull it locally but do you have an idea yourself @JeppeTrip?

2021-01-08 11:41 UTC, objmj-itminds commented on Web/obj/.EntityFrameworkCore.targets
> +﻿<?xml version="1.0" encoding="utf-8"?>
This file should be gitignored as it comes from the `obj` dir from what I can tell. Care to check the settings and maybe update the .girignore file?
You might also have to manually delete this file, which you can do like this
```sh
git rm  Web/obj/.EntityFrameworkCore.targets
```

2021-01-08 11:41 UTC, objmj-itminds commented on backend/Domain/Entities/Refill.cs
> +    public int CouponNumber { get; set; }
I want a relation to the Coupon instead of this.

2021-01-08 11:41 UTC, objmj-itminds commented on backend/Domain/Entities/Coupon.cs
> +  }
I would like to have added the coupon number to be different from the "ID" but still be unique, which you might have to change in the fluent config.

2021-01-08 11:41 UTC, objmj-itminds commented on docs/entity-datamodel.md
> +@startuml
This isn't fully up to date with your current data model.

2021-01-08 11:41 UTC, objmj-itminds commented on docs/entity-datamodel.md
> +### Building
I will take the liberty to add content here—no need to edit this.

2021-01-08 11:59 UTC, JeppeTrip commented on docs/entity-datamodel.md
> +### Building
So I shouldn't add the entities from the datamodel as headings here?

2021-01-08 12:14 UTC, objmj-itminds commented on docs/entity-datamodel.md
> +### Building
Nono - I'll just commit some description :) just let this be.

2021-01-08 12:19 UTC, JeppeTrip commented on backend/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
> -﻿// <auto-generated />
I think it comes down to how the autogeneration of the file functions. It might be that the entire file is generated and new entity definitions are added in between the old ones and thus moving everything around? That is my best guess anyways. That doesn't really explaing why the using statements have been replaced though.

2021-01-08 12:27 UTC, objmj-itminds commented on backend/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
> -﻿// <auto-generated />
Let's keep an eye out for this, but accept it for now, as it is the first time we are touching the Entities and with a lot of changes at that.

2021-01-08 12:28 UTC, objmj-itminds submitted a review, later dismissed

2021-01-08 12:39 UTC, objmj-itminds commented on .gitignore
> +Web/obj/.EntityFrameworkCore.targets
/backend/.gitignore#L27 should be covered here. But alas, we saw it wasn't. At any rate, localize the gitignore, so use the file in the backend dir.

2021-01-08 22:44 UTC, objmj-itminds submitted a review, later dismissed

2021-01-10 21:18 UTC, objmj-itminds approved these changes

2021-01-11 08:56 UTC, ChristopherSchmidtItm approved these changes

2021-01-11 09:02 UTC, merged