Feature/co 73
IT-Minds/client_comby_oilcontrols pull request #73
Opened 2021-01-21 09:16 UTC by DanielVelando

2021-01-21 17:25 UTC, objmj-itminds requested changes
Just some minor adjustment. The most important thing is nailing the imports and styles of the DatePicker component; I feel like something is amiss.

2021-01-21 17:25 UTC, objmj-itminds commented on frontend/src/components/DatePicker/DatePicker.tsx
> +  onChange: (date: Date) => any;
use void instead of any.

2021-01-21 17:25 UTC, objmj-itminds commented on frontend/src/components/DatePicker/DatePicker.tsx
> +const DatePicker = ({
Remember to use FC type for components; it is important to use if libraries require that specific JSX.Element type.

2021-01-21 17:25 UTC, objmj-itminds commented on frontend/src/components/DatePicker/DatePicker.tsx
> +import "./DatePicker.module.css";
I don't think these styles are used correctly. Have you seen them work? 
If I am correct, you must specify an object and use the className attribute on the component.

2021-01-21 17:25 UTC, objmj-itminds commented on frontend/src/components/DatePicker/DatePicker.tsx
> +  ...props
to get this, what you want to do is

```typescript
const DatePick: FC<Props & Partial<REACTDATEPICKERPROPTYPE>> ...
```
This way, you get the component fully typed while still using spread to get any other props.

2021-01-21 17:25 UTC, objmj-itminds commented on frontend/src/components/OrderRefill/OrderRefillComp.tsx
> +import "react-datepicker/dist/react-datepicker.css";
So why is this style import in this place and not inside the component itself?

2021-01-21 17:25 UTC, objmj-itminds commented on frontend/src/pages/demo/co73orderrefill.tsx
> +      awaitCallback(async () => {
This does not need to work offline—no need to use this hook. Well thought tho, just not needed :)

2021-01-22 06:22 UTC, DanielVelando commented on frontend/src/components/OrderRefill/OrderRefillComp.tsx
> +import "react-datepicker/dist/react-datepicker.css";
My bad, forgot to remove it

2021-01-22 08:05 UTC, objmj-itminds approved these changes

2021-01-22 08:05 UTC, merged