Feature/co 77
IT-Minds/client_comby_oilcontrols pull request #74
Opened 2021-01-21 10:38 UTC by DanielVelando

2021-01-21 17:40 UTC, objmj-itminds requested changes

2021-01-21 17:40 UTC, objmj-itminds commented on frontend/src/components/DailyTemperature/AddDailyTemperature.tsx
> +              onChange={e => updateLocalForm(parseInputToNumber(e.target.value), "regionId")}>
`parseInputToNumber` isn't the right thing to use here as it returns a float with 2 decimals. `Number.parseInt` is better suited as you know the id is an int.

2021-01-21 17:40 UTC, objmj-itminds commented on frontend/src/components/DailyTemperature/AddDailyTemperature.tsx
> +              regions.every(r => localAddDailyTemperatureForm.regionId !== parseInputToNumber(r.id))
`parseInputToNumber` isn't the right thing to use here as it returns a float with 2 decimals. `Number.parseInt` is better suited as you know the id is an int.

2021-01-21 17:40 UTC, objmj-itminds commented on frontend/src/components/DailyTemperature/AddDailyTemperature.tsx
> +              onChange={date => setDate(date)}
Nitpicking again.

When the parameter of your function is the same as provided by the callback, you can write
```typescript
   onChange={setDate}
```

2021-01-21 17:40 UTC, objmj-itminds commented on frontend/src/components/DailyTemperature/AddDailyTemperature.tsx
> +            <Input
Look into 
`<InputGroup>` and `<InputRightAddon>`  so we can get a degree symbol. 
_Hint: the degree symbol should come from i18n as it might differ from locale to locale._

2021-01-22 09:06 UTC, DanielVelando commented on frontend/src/components/DailyTemperature/AddDailyTemperature.tsx
> +            <Input
I've added a hardcoded degree symbol for now if that's okay?

2021-01-23 07:06 UTC, objmj-itminds approved these changes

2021-01-23 07:06 UTC, merged