WIP/CO-108 Expand datamodel to support debtors
IT-Minds/client_comby_oilcontrols pull request #97
Opened 2021-01-26 12:28 UTC by JeppeTrip

2021-01-26 12:31 UTC, JeppeTrip commented on backend/Infrastructure/Persistence/Configurations/LocationConfigurations.cs
> +
I'm not sure how to define the relationship we want between locations and debtors. So if someone could help me out here that would be nice.

2021-01-26 13:52 UTC, objmj-itminds commented on backend/Infrastructure/Persistence/Configurations/LocationConfigurations.cs
> +
```csharp
builder.HasOne<Debtor>(e => e.Debtor)
        .WithMany(e => e.Locations);
builder.HasOne<Debtor>(e => e.UpcomingDebtor)
        .WithMany(e => e.Locations)
        .IsRequired(false);
builder.HasOne<Debtor>(e => e.BaseDebtor)
        .WithMany(e => e.Locations)
        .IsRequired(false);
```
Something like this maybe.

2021-01-26 14:22 UTC, JeppeTrip commented on backend/Infrastructure/Persistence/Configurations/LocationConfigurations.cs
> +
Turns out it is not possible to have more than one relationship defined. So I added 3 location lists to the debtor, basic one, one for upcoming locations and one for the locations that the debtors administer.

2021-01-26 15:07 UTC, objmj-itminds commented on backend/Infrastructure/Persistence/Configurations/LocationConfigurations.cs
> +
Can you try this instead? You would need a unique constraint on the LocationId and Type in the LocationDebtor entity
![image](https://user-images.githubusercontent.com/17781340/105862828-86020080-5ff0-11eb-9dac-21caa5aad487.png)

2021-01-27 19:25 UTC, objmj-itminds requested changes
Minor adjustment regarding a unique constraint.

2021-01-27 19:25 UTC, objmj-itminds commented on backend/Infrastructure/Persistence/Configurations/LocationDebtorConfiguration.cs
> +        .IsRequired(true);
I think there needs to be a restriction on the type as well. So that a unique constraint forcing there to be maximum one of each type. This way, we cover the business logic 100%

2021-01-28 11:14 UTC, objmj-itminds submitted a review, later dismissed

2021-01-28 12:42 UTC, objmj-itminds approved these changes

2021-01-28 12:45 UTC, merged