Feature/co 100
IT-Minds/client_comby_oilcontrols pull request #99
Opened 2021-01-27 06:43 UTC by DanielVelando

2021-01-27 19:19 UTC, objmj-itminds requested changes
Take a look at the 5 warnings from the CI pipeline.

2021-01-27 19:19 UTC, objmj-itminds commented on frontend/src/components/LocationHistory/LocationHistoryComp.tsx
> +            <tr key={lh.id}>
Use the Chakra components instead of the base ones.

2021-01-29 08:26 UTC, DanielVelando commented on frontend/src/components/LocationHistory/LocationHistoryComp.tsx
> +            <tr key={lh.id}>
Well spotted!

2021-01-29 10:58 UTC, objmj-itminds approved these changes

2021-01-29 10:58 UTC, merged